### ISSUE TITLE
Running tutorial on fresh installed python environment fails

### ISSUE THREAD

**Issue by rchavp** [pyedifice/pyedifice#135]
Hi,

I'm interested in this project and while trying to run the tutorial I kept getting the same error again and again.

This is my setup:
```
conda create --name edifice python=3.10
conda activate edifice
pip install PySide6
pip install pyedifice
```
Then I copy/pasted the code from the tutorial https://www.pyedifice.org/tutorial into the file tutorial.py, and tried to run the example like this:
```
python -m edifice tutorial.py MyApp
```

and get this error immediately:
```
Traceback (most recent call last):
  File "/home/me/miniconda3/envs/edifice/lib/python3.10/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/me/miniconda3/envs/edifice/lib/python3.10/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/projects/play/tutorial.py", line 1, in <module>
    import edifice as ed
  File "/projects/play/tutorial.py", line 2, in <module>
    from edifice import Label, TextInput, View
ImportError: cannot import name 'Label' from partially initialized module 'edifice' (most likely due to a circular import) (/projects/play/tutorial.py)
```

I also tried with a fresh conda env with python 3.11 and got the same error.

My machine is a Linux Kubuntu 22.04, with an up to date Miniconda setup. I use python heavily for other projects and everything else works on my machine.

**Comment by rchavp** [comment]
My apologies, I found this is not an issue with edifice. I'm closing the issue
