### ISSUE TITLE
Tutorial crashes with _component.py line 730 match el: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Code4SAFrankie** [pyedifice/pyedifice#182]
Running the tutorial.py program crashes with this error:

```
C:\WPy64-39100\python-3.9.10.amd64>.\python.exe -m edifice d:\ebackup\work\python\edifice_test.py MyApp
Traceback (most recent call last):
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\site-packages\edifice\__init__.py", line 132, in <module>
    from ._component import Element, component, Reference
  File "C:\WPy64-39100\python-3.9.10.amd64\lib\site-packages\edifice\_component.py", line 730
    match el:
          ^
SyntaxError: invalid syntax
```

Where edifice_test.py is:

```
from edifice import App, Label, TextInput, HBoxView, Window, component

@component
def MyApp(self):
    with Window(): # Top of every App must be a Window
        with HBoxView():
            Label("Measurement in meters:")
            TextInput("")
            Label("Measurement in feet:")

if __name__ == "__main__":
    App(MyApp()).start()
```

**Comment by jamesdbrock** [comment]
Hi @Code4SAFrankie , Edifice requires Python [3.10](https://docs.python.org/3/whatsnew/3.10.html).

In your case you ran with Python 3.9 and it crashed because Python 3.9 does not support `match` `case`.
