### ISSUE TITLE
Error on using dynamic loading

### ISSUE THREAD

**Issue by dhnam** [pyedifice/pyedifice#44]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/vscode/.local/lib/python3.11/site-packages/watchdog/observers/api.py", line 204, in run
    self.dispatch_events(self.event_queue)
  File "/home/vscode/.local/lib/python3.11/site-packages/watchdog/observers/api.py", line 380, in dispatch_events
    handler.dispatch(event)
  File "/home/vscode/.local/lib/python3.11/site-packages/watchdog/events.py", line 276, in dispatch
    {
  File "/home/vscode/.local/lib/python3.11/site-packages/edifice/runner.py", line 119, in on_modified
    if isinstance(observer, FSEventsObserver) and event.is_directory:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

Looks like importing `watchdog.observers.fsevents.FSEventsObserver` caused `ModuleNotFoundError` somehow (I don't know why so I added it to issue of watchdog: https://github.com/gorakhargosh/watchdog/issues/1008) and messed up

```python
try:
    from watchdog.observers.fsevents import FSEventsObserver
except ImportError:
    FSEventsObserver = None
```
in `runner.py`.

I monkey-patched the code like this - 
```python
        def on_modified(self, event):
            if FSEventsObserver is not None and isinstance(observer, FSEventsObserver) and event.is_directory:
```
(line 117-118) and it worked properly

Maybe something related to my installation (I install this on codespace with devcontainer and quite a lot of `apt install` mess) or installation of watchdog went something wrong.

(Oh and plus - this project doesn't requires watchdog in `requirements.txt` which made me install watchdog manually, would be nice if it is installed along with edifice when I just `pip install pyedifice`.)

**Comment by dhnam** [comment]
dupe of https://github.com/pyedifice/pyedifice/issues/18. Sorry.
