### ISSUE TITLE
should_update() bug

### ISSUE THREAD

**Issue by jamesdbrock** [pyedifice/pyedifice#85]
```
Encountered error while rendering. Unwinding changes.
Exception in callback App._defer_rerender.<locals>.rerender_callback() at /nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/app.py:199
handle: <Handle App._defer_rerender.<locals>.rerender_callback() at /nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/app.py:199>
Traceback (most recent call last):
  File "/nix/store/s6fgyqbk8vn1014daznm5kqx90xdn86x-python3-3.10.13/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/app.py", line 202, in rerender_callback
    self._request_rerender(list(els), {})
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/app.py", line 232, in _request_rerender
    render_result = self._render_engine._request_rerender(components)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 700, in _request_rerender
    widget_trees = self._gen_widget_trees(components, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 691, in _gen_widget_trees
    widget_trees.append(self._render(component, render_context))
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 665, in _render
    render_context.widget_tree[component] = self._update_old_component(
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in _recycle_children
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in <listcomp>
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 524, in _get_child_using_key
    self._update_old_component(d[key], newchild, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in _recycle_children
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in <listcomp>
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 524, in _get_child_using_key
    self._update_old_component(d[key], newchild, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in _recycle_children
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in <listcomp>
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 524, in _get_child_using_key
    self._update_old_component(d[key], newchild, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 544, in _recycle_children
    self._update_old_component(old_children[0], component.children[0], render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in _recycle_children
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in <listcomp>
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 524, in _get_child_using_key
    self._update_old_component(d[key], newchild, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 665, in _render
    render_context.widget_tree[component] = self._update_old_component(
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in _recycle_children
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in <listcomp>
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 524, in _get_child_using_key
    self._update_old_component(d[key], newchild, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 544, in _recycle_children
    self._update_old_component(old_children[0], component.children[0], render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 665, in _render
    render_context.widget_tree[component] = self._update_old_component(
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 544, in _recycle_children
    self._update_old_component(old_children[0], component.children[0], render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in _recycle_children
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 557, in <listcomp>
    children = [self._get_child_using_key(key_to_old_child, new_child._key, new_child, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 524, in _get_child_using_key
    self._update_old_component(d[key], newchild, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 513, in _update_old_component
    rerendered_obj = self._render(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 625, in _render
    ret = self._render_base_component(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 580, in _render_base_component
    children = self._recycle_children(component, render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 544, in _recycle_children
    self._update_old_component(old_children[0], component.children[0], render_context)
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/engine.py", line 511, in _update_old_component
    if component._should_update(newprops, {}):
  File "/nix/store/jimxmklvfixbav2cbc55risln5fy7f35-python3-3.10.13-env/lib/python3.10/site-packages/edifice/_component.py", line 489, in _should_update
    if v2 is None or v2 != v:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by jamesdbrock** [comment]
This is happening because we're allowing Numpy arrays as props. We should stop doing that.

https://github.com/pyedifice/pyedifice/blob/fc88379fd21ab49be12c11f4aab8953579370a8f/edifice/base_components/base_components.py#L67

Also #50

**Comment by jamesdbrock** [comment]
Removed numpy dependency.
